spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ec2-34-236-215-156.compute-1.amazonaws.com:5432/ddji4883tepm4o?sslmode=require
spring.datasource.username=pagnfxnilgyvvl
spring.datasource.password=e661a2f2516e8b017fc40f43abbee2f8c0d1bc85d30468c60061146817ba67bd

security.user.name=navioKawagoe
security.user.password=8150